"""
Regenerate the agent reasoning-trace log used for the Agentic Workflow stretch
feature. Runs the agent on a fixed set of messages that exercise every routing
path and writes the traces to logs/agent_traces.md.

    python scripts/generate_traces.py

Committed so the log is reproducible: rerun it any time src/agent.py changes.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from src.agent import Agent, format_trace

# Each message is chosen to demonstrate a different path through the chain.
MESSAGES = [
    ("Recommendation request", "chill lofi for studying, acoustic"),
    ("Knowledge question (genre)", "what is lofi?"),
    ("Knowledge question (system)", "how are recommendations scored?"),
    ("Re-route: question phrasing, no doc match, but taste parsed",
     "can you play something euphoric?"),
    ("Graceful fallback: nothing parsed, nothing grounded", "polka chaotic gibberish"),
]

OUT_PATH = os.path.join(ROOT, "logs", "agent_traces.md")


def main() -> None:
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    agent = Agent()
    lines = [
        "# Agent Reasoning Traces",
        "",
        "Generated by `scripts/generate_traces.py` (deterministic, offline). Each",
        "block shows a user message, the agent's step-by-step reasoning "
        "(plan → act → check → respond), and the final reply.",
        "",
    ]
    for label, message in MESSAGES:
        result = agent.run(message)
        lines.append(f"## {label}")
        lines.append("")
        lines.append(f"**User:** {message}")
        lines.append("")
        lines.append(f"**Intent chosen:** `{result.intent}`")
        lines.append("")
        lines.append("**Reasoning trace:**")
        lines.append("")
        lines.append("```")
        lines.append(format_trace(result))
        lines.append("```")
        lines.append("")
        lines.append("**Reply:**")
        lines.append("")
        lines.append("```")
        lines.append(result.reply)
        lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("")
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
